#!/bin/bash
#
# bash script that spins Java wrapper up on the algorithm here
#
# First, find out where we are

case $0 in
         /*)  SHELLFILE=$0 ;;
        ./*)  SHELLFILE=${PWD}${0#.} ;;
        ../*) SHELLFILE=${PWD%/*}${0#..} ;;
          *)  SHELLFILE=$(type -P $0) ; if [ ${SHELLFILE:0:1} != "/" ]; then SHELLFILE=${PWD}/$SHELLFILE ; fi ;;
esac
SHELLDIR=${SHELLFILE%/*}
SPADIR=${SHELLDIR}/../..

# Then crank java using the jar files and the wrapper

SPAJAR=$SPADIR/wrapper/lib/spa.jar
INTERPJAR=$SPADIR/wrapper/lib/interp.jar
NCSJAR=$SPADIR/wrapper/lib/ncs.jar
NSLSJAR=$SPADIR/wrapper/lib/nsls.jar

java -classpath $SPAJAR:$INTERPJAR:$NCSJAR:$NSLSJAR gov/nasa/gsfc/nisgs/spa/CommandLineRunAlgorithm $SHELLDIR/installation.xml $*
